In [4]:
import numpy as np
import pandas as pd
d={'A':[1,2,np.nan],
'B':[5,np.nan,np.nan],
'C':[1,2,3]
  }
df=pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [5]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [6]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [7]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [8]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [9]:
df.fillna(value='Filling Value')

               A              B  C
0            1.0            5.0  1
1            2.0  Filling Value  2
2  Filling Value  Filling Value  3

In [10]:
df=pd.DataFrame(d)
a=df['A'].fillna(value=df['A'].mean())

In [11]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
a

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [13]:
df['A'].fillna(value=df['A'].mean(),inplace=True)
df

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_2792\736070674.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value=df['A'].mean(),inplace=True)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [14]:
data = {
    'Company':['Google', 'Google', 'MSFT', 'FB','FB','IBM'],
    'Person': ['Sam','Nihad','Any','Van','Rakib','Ovi'],
    'Sales': [200, 120, 340, 124, 243, 350]
}
df=pd.DataFrame(data)
df

  Company Person  Sales
0  Google    Sam    200
1  Google  Nihad    120
2    MSFT    Any    340
3      FB    Van    124
4      FB  Rakib    243
5     IBM    Ovi    350

In [18]:
byComp=df.groupby('Company')
byComp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [19]:
byComp.sum()

           Person  Sales
Company
FB       VanRakib    367
Google   SamNihad    320
IBM           Ovi    350
MSFT          Any    340

In [ ]:
df

In [20]:
byComp.std()

ValueError: could not convert string to float: 'Sam'

In [17]:
df.groupby('Company')

In [21]:
df=pd.DataFrame(data)
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
Google        2      2
IBM           1      1
MSFT          1      1

In [22]:
df.groupby('Company').describe()

        Sales
        count   mean        std    min     25%    50%     75%    max
Company
FB        2.0  183.5  84.145707  124.0  153.75  183.5  213.25  243.0
Google    2.0  160.0  56.568542  120.0  140.00  160.0  180.00  200.0
IBM       1.0  350.0        NaN  350.0  350.00  350.0  350.00  350.0
MSFT      1.0  340.0        NaN  340.0  340.00  340.0  340.00  340.0

In [23]:
df1=pd.DataFrame(np.random.randint(1,20,size=(4,3)),[1,2,3,4],['W','X','Y'])

In [24]:
df2 = pd.DataFrame(np.random.randint(20,40, size = (4, 3)), [5,6,7,8], ['W', 'X', 'Y'])

In [30]:
df3=pd.DataFrame(np.random.randint(40,60, size = (4, 3)), [9,10,11,12], ['W', 'X', 'Y'])

In [26]:
df1

    W   X   Y
1   8   5  19
2   5   4   7
3  16  10  13
4   3   6  18

In [27]:
df2

    W   X   Y
5  33  34  34
6  34  24  26
7  31  32  28
8  36  22  21

In [31]:
df3

     W   X   Y
9   57  58  41
10  40  57  56
11  56  54  50
12  51  46  45

In [32]:
frame=[df1,df2,df3]
pd.concat(frame)

     W   X   Y
1    8   5  19
2    5   4   7
3   16  10  13
4    3   6  18
5   33  34  34
6   34  24  26
7   31  32  28
8   36  22  21
9   57  58  41
10  40  57  56
11  56  54  50
12  51  46  45

In [35]:
pd.concat(frame,axis=1)

       W     X     Y     W     X     Y     W     X     Y
1    8.0   5.0  19.0   NaN   NaN   NaN   NaN   NaN   NaN
2    5.0   4.0   7.0   NaN   NaN   NaN   NaN   NaN   NaN
3   16.0  10.0  13.0   NaN   NaN   NaN   NaN   NaN   NaN
4    3.0   6.0  18.0   NaN   NaN   NaN   NaN   NaN   NaN
5    NaN   NaN   NaN  33.0  34.0  34.0   NaN   NaN   NaN
6    NaN   NaN   NaN  34.0  24.0  26.0   NaN   NaN   NaN
7    NaN   NaN   NaN  31.0  32.0  28.0   NaN   NaN   NaN
8    NaN   NaN   NaN  36.0  22.0  21.0   NaN   NaN   NaN
9    NaN   NaN   NaN   NaN   NaN   NaN  57.0  58.0  41.0
10   NaN   NaN   NaN   NaN   NaN   NaN  40.0  57.0  56.0
11   NaN   NaN   NaN   NaN   NaN   NaN  56.0  54.0  50.0
12   NaN   NaN   NaN   NaN   NaN   NaN  51.0  46.0  45.0

In [36]:
left={
    'key':['k0','k1','k2','k3'],'A':[10,20,30,40],'B':[1,2,3,4]}

In [37]:
right = {
    'key':['k0','k1','k2','k3'],
    'C':[100,200,300,400],
    'D':[11,12,13,14]
}

In [38]:
left=pd.DataFrame(left)
right=pd.DataFrame(right)
left

  key   A  B
0  k0  10  1
1  k1  20  2
2  k2  30  3
3  k3  40  4

In [39]:
right

  key    C   D
0  k0  100  11
1  k1  200  12
2  k2  300  13
3  k3  400  14

In [40]:
pd.merge(left,right,on='key')

  key   A  B    C   D
0  k0  10  1  100  11
1  k1  20  2  200  12
2  k2  30  3  300  13
3  k3  40  4  400  14

In [56]:
left = {
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']
}

In [57]:
right = {
    'C':['C0','C1','C2'],
    'D':['D0','D1','D2']
}

In [58]:
left=pd.DataFrame(left,index=['k0','k1','k2'])
right=pd.DataFrame(right,index=['k0','k2','k3'])

In [59]:
left

     A   B
k0  A0  B0
k1  A1  B1
k2  A2  B2

In [60]:
right

     C   D
k0  C0  D0
k2  C1  D1
k3  C2  D2

In [61]:
left.join(right,how='inner')

     A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

In [62]:
df=pd.DataFrame({
    'col1':[444,555,666,444],'col2':[1,2,3,4],'col3':['abc','def','ghi','xyz']})

In [63]:
df

   col1  col2 col3
0   444     1  abc
1   555     2  def
2   666     3  ghi
3   444     4  xyz

In [64]:
df['col1'].unique()

array([444, 555, 666])

In [65]:
df['col1'].nunique()

3

In [66]:
df['col1'].value_counts()

col1
444    2
555    1
666    1
Name: count, dtype: int64

In [67]:
def times2(x):
    return 2*x

In [68]:
df['col2'].apply(times2)

0    2
1    4
2    6
3    8
Name: col2, dtype: int64

In [69]:
df['col2'].apply(lambda x:x**2)

0     1
1     4
2     9
3    16
Name: col2, dtype: int64

In [80]:
import numpy as np
a=np.random.randint(1,10,size=(5))
a

array([3, 5, 1, 9, 5], dtype=int32)

In [84]:
x=np.reverse(a, kind='mergesort')
x

AttributeError: module 'numpy' has no attribute 'reverse'